# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: Default
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
# - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'
- bash: echo This script could use $SYSTEM_ACCESSTOKEN
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
- powershell: | 
    Write-Host "This is a script that could use $env:SYSTEM_ACCESSTOKEN"
    Write-Host "$env:SYSTEM_ACCESSTOKEN = $(System.AccessToken)"
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)